### ISSUE TITLE
Brand-new `nervos.org` website design

### ISSUE THREAD

**Issue by WhiteMinds** [Magickbase/nervos-official-website#1]
Requirement document and design draft (first draft):
https://docs.google.com/document/d/1oSAeXAdXByPKNwomVrlGNAGmMOqvNvq9KJZeGYhg_ng/edit

The old version of https://www.nervos.org/ is written in WordPress, which is not convenient for cooperation and development, so the new version will start the technology architecture again.

Then the first thing to do is choosing technology type.

**Comment by Keith-CY** [comment]
Homepage: https://www.figma.com/file/NuMAXnrvH4SQVRJfuZhZVw/Nervos.org-R3?node-id=0%3A1&t=YQ7aZZfS4l3C8aix-1
Separate pages: https://www.figma.com/file/NuMAXnrvH4SQVRJfuZhZVw/Nervos.org-R3?node-id=2403%3A462&t=YQ7aZZfS4l3C8aix-1

Fonts:
[Articulat_CF.zip](https://github.com/Magickbase/nervos-official-website/files/10857541/Articulat_CF.zip)

**Comment by WhiteMinds** [comment]
The basic structure of the project has been completed, and we can enter the stage of collaborative development, the relevant code has been pushed to the repo, next I will create some issues to split and assign tasks.

main branch preview: https://nervos-official-website.vercel.app/

An issue was discovered during deployment, so a new fix commit was added where `pageExtensions` were configured in `next.config.mjs`, but this seems to have caused the i18n selection to fail, which will be addressed later.

**Comment by WhiteMinds** [comment]
> main branch preview: https://nervos-official-website.vercel.app/
> 
> Probably because I don't have access to this repo to install the vercel app, I can't use this repo as a deployment target in vercel, so now it's deployed using the main branch of my fork repository.

Now https://nervos-official-website.vercel.app/ is the main branch of the repo, the deployment domain of my forked repo is https://wm-nervos-official-website.vercel.app/ .
