### ISSUE TITLE
Edu hub article link preview should show article info (currently shows main site info)

### ISSUE THREAD

**Issue by matt-nervos** [Magickbase/nervos-official-website#106]
Headline should be article headline
Body should be sub-headline

<img width="461" alt="image" src="https://user-images.githubusercontent.com/88007636/232136740-2455bab7-d6d8-4bf1-9929-43ffb4785481.png">

**Comment by matt-nervos** [comment]
@WhiteMinds any update?

**Comment by WhiteMinds** [comment]
> @WhiteMinds any update?

Recently, I have been focusing on handling this task: https://github.com/Magickbase/neuron-public-issues/issues/99.
I will need to wait until this task is completed before I can proceed with other tasks.
