### ISSUE TITLE
table doesn't render on Education hub

### ISSUE THREAD

**Issue by matt-nervos** [Magickbase/nervos-official-website#107]
<img width="604" alt="image" src="https://user-images.githubusercontent.com/88007636/232254181-2adf963c-f49f-4e2a-85d4-e5bc26067f22.png">
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/88007636/232254201-be8edc65-a833-4e6d-b5f9-b2899be4b7e2.png">

**Comment by WhiteMinds** [comment]
PR: #135

**Comment by matt-nervos** [comment]
implemented
