### ISSUE TITLE
Occupied CKB calculation is broken on main page

### ISSUE THREAD

**Issue by matt-nervos** [Magickbase/nervos-official-website#109]
![image](https://user-images.githubusercontent.com/88007636/233160058-fb4abf75-f8e2-4dd3-b481-2bd012cf3d09.png)

**Comment by matt-nervos** [comment]
today all are showing as "loading" 
<img width="500" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/88007636/756d16a1-3353-4434-a1bb-bee726bd477a">

**Comment by Keith-CY** [comment]
> today all are showing as "loading" <img alt="image" width="500" src="https://user-images.githubusercontent.com/88007636/237557313-756d16a1-3353-4434-a1bb-bee726bd477a.png">

The API of CKB explorer is broken due to improper operation, we're migrating to the backup service

**Comment by Keith-CY** [comment]
> > today all are showing as "loading" <img alt="image" width="500" src="https://user-images.githubusercontent.com/88007636/237557313-756d16a1-3353-4434-a1bb-bee726bd477a.png">
> 
> The API of CKB explorer is broken due to improper operation, we're migrating to the backup service

It's recovered
