### ISSUE TITLE
[Bug] Unexpected subtitle in NervosEdu articles

### ISSUE THREAD

**Issue by alejandroRbit** [Magickbase/nervos-official-website#178]
In NervosEdu articles, the website creates a subtitle between the title and the cover image with part of the first paragraph of the article.

![Nervosorgissue](https://github.com/Magickbase/nervos-official-website/assets/94946624/c29c7ef3-d3cc-4160-8e1f-63ac32dae790)

Reference (although it happens in other articles as well): https://www.nervos.org/knowledge-base/what_are_payment_channels

**Comment by WhiteMinds** [comment]
PR: #185 and https://github.com/NervosEducationHub/EducationHubArticles/pull/28

**Comment by Keith-CY** [comment]
With this fix, The `excerpt` field in an article's meta should be replaced by `subtitle` in the future, as https://github.com/NervosEducationHub/EducationHubArticles/pull/28/files did

cc @alejandroRbit @matt-nervos
