### ISSUE TITLE
Some details to be confirmed

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/nervos-official-website#2]
### Header
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/7271329/221504437-17c85881-76f9-4c1f-8d08-735fdb58a853.png">

  1. It's fixed on the screen and 100% wide on an extra wide screen instead of being centered;
  2. <del>It looks like a gross glass, as https://codepen.io/aja9104/pen/ARJyJb<del/>
  3. Color of the elements is inverted based on the background, as https://codepen.io/ainalem/pen/jGgmpE

### Footer
  1. slide in when the last section of the body is scrolled into the screen

### Body
  1. The sections are scrolled one by one, as https://codepen.io/andrejsharapov/pen/xBGKrr;
  2. the scroll could be triggered by arrow buttons;
  3. Background color fades in/out on scrolling, not moved along with the page;
  4. Each section is 100% height. The next section won't appear until scrolling starts.

### Other Elements
  1. Conway's game of life
    1. on the main page, game and its controller are fixed on the screen, won't move along with scrolling;
    2. game is draggable;
	3. intersection with the title is allowed
    <img width="483" alt="image" src="https://user-images.githubusercontent.com/7271329/221513228-db7a050d-8b88-42f8-bc95-d7326d6c00f2.png">
	4. intersection with the subtitle/text is disallowed on page mount, but it's allowed to be intersected along with the cells growing, and user can drag it away for reading
    <img width="502" alt="image" src="https://user-images.githubusercontent.com/7271329/221513374-b7b01e49-3742-476b-89e9-d24c0ddefa3c.png">
    5. if the game is not triggered by user for 10s, it starts itself for 2s and stop, repeatedly until the user realized it's interactable;
    6. on the separate pages, conway's game of life is shown as a static image, and fixed on the page instead of the screen, moved along with scrolling;
    7. the image of cells will be a bit wider than designed to make it more natural(not clipped) on widescreen
    <img width="615" alt="image" src="https://user-images.githubusercontent.com/7271329/221516090-4f8dd6c8-8f0d-4602-9c7f-2be802b433e8.png">

  2. element on the left bottom corner is fixed on the screen instead of the page
  
  <img width="358" alt="image" src="https://user-images.githubusercontent.com/7271329/221514361-6ae75fcf-664b-4e0e-8e13-646533015149.png">

**Comment by WhiteMinds** [comment]
Basically completed.
