### ISSUE TITLE
Can't load og:image, twitter:image

### ISSUE THREAD

**Issue by yixyxiu** [Magickbase/nervos-official-website#205]
1、博客文章页面：
```
<meta property="og:image" content="/education_hub_articles/ckb_blockchain_developers_dream/images/image1.png">
<meta property="twitter:image" content="/education_hub_articles/ckb_blockchain_developers_dream/images/image1.png">
```
中使用相对路径时，社交媒体无法正确解析和加载图像，因为它们无法确定图像的完整绝对路径。

2、首页里没有加入og:image, twitter:image这两个meta标签，所以在社交媒体输入nervos.org时无法显示卡片：
![image](https://github.com/Magickbase/nervos-official-website/assets/87553548/66dcc8e4-362f-46ee-8936-d060cf50b66c)

![image](https://github.com/Magickbase/nervos-official-website/assets/87553548/45954bd0-c4c0-4f3a-aedd-f6679ad24362)

Learn more:
[https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image)

**Comment by WhiteMinds** [comment]
Oh, thanks for the feedback, I will fix it.

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/nervos-official-website/pull/211
