### ISSUE TITLE
Add Neuron direct download to website/wallet section

### ISSUE THREAD

**Issue by Lysis1501** [Magickbase/nervos-official-website#237]
GitHub is a very intimidating platform to less tech-savvy users and crypto newcomers - there should be no need for either to leave the foundation website and dig through a repo in order to download the latest Neuron version.

**Comment by Keith-CY** [comment]
Hi @Lysis1501 

Thanks for the advice. We are indeed building a page as Neuron's entry that includes downloading, notification, user guide, and troubleshooting.

The task is tracked by https://github.com/Magickbase/neuron-public-issues/issues/99 and the page is being developed in https://github.com/Magickbase/neuron-troubleshooting

I'll update this thread when it's live.

**Comment by matt-nervos** [comment]
@Keith-CY  is it a good time to link to https://neuron.magickbase.com/ on the wallets page?

**Comment by Keith-CY** [comment]
> @Keith-CY is it a good time to link to [neuron.magickbase.com](https://neuron.magickbase.com/) on the wallets page?

Sure, I will update it today

**Comment by Keith-CY** [comment]
Page will be updated by https://github.com/Magickbase/nervos-official-website/pull/382, and the download link navigates to https://neuron.magickbase.com/ where Neuron can be downloaded according to users' operating system.
