### ISSUE TITLE
Remove "CKB" from homepage

### ISSUE THREAD

**Issue by matt-nervos** [Magickbase/nervos-official-website#251]
It seems like a drastic change should be discussed, suggest to remove the additional "CKB" that was added without discussion
<img width="325" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/88007636/3e5d7213-92d4-449e-ab2c-5ca7d0432cf1">

**Comment by Keith-CY** [comment]
This update will be reverted by https://github.com/Magickbase/nervos-official-website/pull/252
