### ISSUE TITLE
[Bug] Article subtitles does not recognize hyperlinks.

### ISSUE THREAD

**Issue by alejandroRbit** [Magickbase/nervos-official-website#296]
The subtitles field does not recognize hyperlinks, and I think neither bold, italic, etc.

![bug](https://github.com/Magickbase/nervos-official-website/assets/94946624/4e50f8de-1193-4e5b-adee-833b9b6cf8b1)

Code ref: https://github.com/NervosEducationHub/EducationHubArticles/blob/main/surprisingly_secondary_issuance_is_not_inflationary/index.md

**Comment by Keith-CY** [comment]
Please check this issue, it could be done by https://github.com/Magickbase/nervos-official-website/blob/develop/src/utils/markdownToHtml.ts @zhangyouxin

**Comment by zhangyouxin** [comment]
> Please check this issue, it could be done by https://github.com/Magickbase/nervos-official-website/blob/develop/src/utils/markdownToHtml.ts @zhangyouxin

I'll follow up on this
