### ISSUE TITLE
Update layout of author list

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/nervos-official-website#311]
This issue comes from https://github.com/NervosEducationHub/EducationHubArticles/issues/29#issuecomment-1666934213

---

Now the author list is rough that only the first author is displayed with name
![image](https://github.com/Magickbase/nervos-official-website/assets/7271329/3b5d5308-bab6-43ee-8f52-82f56a228ad7)

By this issue, the author list is expected to be expanded and everyone has his/her name displayed.

The design has been updated at https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&mode=design&t=UVBK1kYzNS4uqKol-0

![image](https://github.com/Magickbase/nervos-official-website/assets/7271329/c857431c-eab5-430f-baaf-220886e81b58)

**Comment by Keith-CY** [comment]
Any update on this @zhangyouxin

**Comment by Keith-CY** [comment]
Any update on this @zhangyouxin

**Comment by zhangyouxin** [comment]
> Any update on this @zhangyouxin

Sorry I didn't get last notice and it's weird this issue is not in my `Assigned` tasks, I'll handle this issue tomorrow

**Comment by zhangyouxin** [comment]
Will be resolved by: https://github.com/Magickbase/nervos-official-website/pull/339
