### ISSUE TITLE
Add "CKB Node Map" to Community sub-section

### ISSUE THREAD

**Issue by matt-nervos** [Magickbase/nervos-official-website#355]
Under the Community sub-section of the Nav bars, suggest to add a link to https://nodes.ckb.dev "CKB Node Map"

**Comment by Keith-CY** [comment]
The link was added by https://github.com/Magickbase/nervos-official-website/pull/361 and a preview is available at https://nervos-official-website-git-add-community-nodes-magickbase.vercel.app/

**Comment by matt-nervos** [comment]
I should have included to add it in the footer as well, can you update it?

**Comment by Keith-CY** [comment]
> I should have included to add it in the footer as well, can you update it?

The link of ckb nodes probe has been added in the footer

![image](https://github.com/Magickbase/nervos-official-website/assets/7271329/9e00935d-a4f5-468e-9c5c-723fe20ee827)
![image](https://github.com/Magickbase/nervos-official-website/assets/7271329/f446cc1c-174d-47e9-9006-bcb2c7ad7427)
![image](https://github.com/Magickbase/nervos-official-website/assets/7271329/8dbfb51b-b41b-408f-a857-ffb0ec6571e3)

**Comment by Keith-CY** [comment]
"CKB Node Probe" is already online.

**Comment by matt-nervos** [comment]
Closing thank you Keith!
