### ISSUE TITLE
[Bug] Knowledge Base categories do not seem to work correctly

### ISSUE THREAD

**Issue by alejandroRbit** [Magickbase/nervos-official-website#381]
Some of the categories on the Knowledge Base website (https://www.nervos.org/knowledge-base) do not seem to work correctly. For example, I have written a couple of articles about CKB's economic model where I added "Economics" as a category (Ref: https://github.com/NervosEducationHub/EducationHubArticles/blob/main/surprisingly_secondary_issuance_is_not_inflationary/index.md?plain=1) and when I click on economics it does not show these articles, it simply shows the original website with the same articles (https://www.nervos.org/knowledge-base?sort_by=economics). However, if you click on oldest post it works correctly (https://www.nervos.org/knowledge-base?sort_by=oldest%20post).

![Github issue](https://github.com/Magickbase/nervos-official-website/assets/94946624/ff9bed2e-d0ca-43e9-838a-27d06511bb79)

**Comment by Keith-CY** [comment]
It was designed to be sorted by the primary category, `popular` in this case. Now being sorted by any field in the category is supported.

Preview: https://www.nervos.org/knowledge-base?sort_by=economics
Commit: https://github.com/Magickbase/nervos-official-website/commit/d6a36e8a434cbc156bb910058d6ad4732be37d19

**Comment by alejandroRbit** [comment]
Great, thank you, have a nice weekend! I close the issue satisfactorily.
