### ISSUE TITLE
Journey page link preview image is underwhelming :D

### ISSUE THREAD

**Issue by matt-nervos** [Magickbase/nervos-official-website#384]
Wondering if there's anything that can be done to improve this, we all put so much effort into the site and this is the link preview image 
<img width="368" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/88007636/a696dae5-f6f7-4573-b984-5916db2ec9bf">

**Comment by Keith-CY** [comment]
We can set an image for the preview, but I'm not sure which one on https://www.nervos.org/journey to pick. IMO, none of these 4 images is suitable for the preview because their backgrounds are transparent. It would be better to design one for the preview specifically.

**Comment by Keith-CY** [comment]
Covers of previews should be added by https://github.com/Magickbase/nervos-official-website/pull/402

Covers expected to be added are as follows:
![CKB](https://github.com/Magickbase/nervos-official-website/assets/7271329/328d3ece-4c84-4440-97d9-afe1ac5f1943)
![Community](https://github.com/Magickbase/nervos-official-website/assets/7271329/cf684604-7f29-4334-aa75-d4127ab2a96b)
![Develpoers](https://github.com/Magickbase/nervos-official-website/assets/7271329/bdb0627b-a14b-4a6c-85e8-88138366816d)
![Foundation](https://github.com/Magickbase/nervos-official-website/assets/7271329/517d262b-4a9b-448e-aed8-d4317215845c)
![Homepage](https://github.com/Magickbase/nervos-official-website/assets/7271329/c3297ca9-0903-4d56-817a-68caf2766543)
![Journey](https://github.com/Magickbase/nervos-official-website/assets/7271329/96baae68-7827-4177-9bdf-42166b18c90c)
![Knowledge_Base](https://github.com/Magickbase/nervos-official-website/assets/7271329/37da9b76-c360-4248-b604-7df77cf35890)
![Learn](https://github.com/Magickbase/nervos-official-website/assets/7271329/3924cd50-4b91-49b0-aca0-041ea0bb3e2f)
![Media_Kit](https://github.com/Magickbase/nervos-official-website/assets/7271329/d634095d-9683-44b0-a064-ca4427e87565)
![Mining](https://github.com/Magickbase/nervos-official-website/assets/7271329/31f847e9-4bf7-4a12-b5eb-22d02f436504)
![Wallets](https://github.com/Magickbase/nervos-official-website/assets/7271329/848da855-c184-4211-869f-9cd2d31d5e8b)

**Comment by Keith-CY** [comment]
<img width="416" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/7271329/33f3a336-240b-4cba-959d-28c6b398f850">

Updates have been deployed to production
