### ISSUE TITLE
Remove "Build Club" from "Developers Page"

### ISSUE THREAD

**Issue by matt-nervos** [Magickbase/nervos-official-website#385]
Hopefully one day I would be able to propose a comment out for this kind of thing, but for now :))

Please remove "Build Club" from this page, as this is Eric's project and has since stopped working with projects building on Godwoken

<img width="213" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/88007636/48d3c813-f4a2-43b0-bc71-1dc4c7fb7ac6">

**Comment by WhiteMinds** [comment]
PR: https://github.com/Magickbase/nervos-official-website/pull/386

**Comment by Keith-CY** [comment]
**Build Club** has been removed from page https://www.nervos.org/developers
