### ISSUE TITLE
[Bug] Error in page numbers on NervosEdu articles website.

### ISSUE THREAD

**Issue by alejandroRbit** [Magickbase/nervos-official-website#387]
On the Nervos Knowledge Base website, when you click on page 3 to see the oldest articles, this appears:

![issue](https://github.com/Magickbase/nervos-official-website/assets/94946624/638bdfd9-b76a-44de-8d42-b7d7274372a7)

REF: https://www.nervos.org/knowledge-base?page=3

**Comment by Keith-CY** [comment]
It has been fixed by https://github.com/Magickbase/nervos-official-website/commit/b267606b853246449a4d1ab587578bf7ff9a33d6

**Comment by alejandroRbit** [comment]
Thank you Keith!
