### ISSUE TITLE
Error 404 in NervosEdu article.

### ISSUE THREAD

**Issue by alejandroRbit** [Magickbase/nervos-official-website#388]
![issue3](https://github.com/Magickbase/nervos-official-website/assets/94946624/968ee7c3-c92f-48d7-a33d-7405317693ec)

![issue2](https://github.com/Magickbase/nervos-official-website/assets/94946624/536eb35b-efc9-49f9-8556-b3b61db2780c)

Ref: https://www.nervos.org/knowledge-base/what_is_a_blockchain_gas_fee?_(explainCKBot)

**Comment by alejandroRbit** [comment]
https://github.com/NervosEducationHub/EducationHubArticles/pull/117

**Comment by Keith-CY** [comment]
The page is available now at https://www.nervos.org/knowledge-base/what_is_a_blockchain_gas_fee_(explainCKBot)

The cover has tiny issue and I will fix it

Meanwhile, `?` is not properly handled, and we should pay attention to this @WhiteMinds

**Comment by Keith-CY** [comment]
The cover(https://github.com/NervosEducationHub/EducationHubArticles/blob/d854c8b7f57086d29bc3070c4d4423875ec3bc39/what_is_a_blockchain_gas_fee_(explainCKBot)/images/image1.png) is not a valid image, please have a check @alejandroRbit 

I'll replace it with https://github.com/NervosEducationHub/EducationHubArticles/commit/6c7bd22745f95a3605d3032f93f54c73ffe89983 as a temporary fix

**Comment by alejandroRbit** [comment]
Thanks Keith, it looks like everything is correct now.

**Comment by WhiteMinds** [comment]
> The page is available now at https://www.nervos.org/knowledge-base/what_is_a_blockchain_gas_fee_(explainCKBot)
> 
> The cover has tiny issue and I will fix it
> 
> Meanwhile, `?` is not properly handled, and we should pay attention to this @WhiteMinds

New issue: https://github.com/Magickbase/nervos-official-website/issues/389
