### ISSUE TITLE
add "Ecosystem" link under CKB in Nav menu

### ISSUE THREAD

**Issue by matt-nervos** [Magickbase/nervos-official-website#410]
link to https://ckbdapps.com/ecosystem

<img width="123" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/88007636/03e7c897-325e-4058-a6e4-c5f5cdfaf11e">

**Comment by Keith-CY** [comment]
Should be added by PR https://github.com/Magickbase/nervos-official-website/pull/412

**Comment by Keith-CY** [comment]
The entry to ecosystem has been online

**Comment by matt-nervos** [comment]
thanks @Keith-CY !
