### ISSUE TITLE
remove "Layer 1 Built for Modularity" from home page

### ISSUE THREAD

**Issue by matt-nervos** [Magickbase/nervos-official-website#411]
This tag line has never attracted much enthusiasm and is merely acceptable.

There have been discussions around the idea of improving it, using something else, but no concept has attracted much interest.

Recently there was an idea to change this to reflect some of the community's interest in connecting CKB to Bitcoin.

In my opinion, the best thing to do is remove this tag line. Based on 6 years of effort to increase awareness and explain CKB and the Nervos Network, a reputation should precede these systems, any effort to sum up all of this in a tag line is at best incomplete, at worst misleading.

**Comment by Keith-CY** [comment]
The first slide on home page is about "modularity", should it be removed entirely, or just remove its subtitle "Layer 1 Built for Modularity"?

**Comment by Keith-CY** [comment]
Should be updated by https://github.com/Magickbase/nervos-official-website/pull/422

**Comment by Keith-CY** [comment]
It's been updated at https://www.nervos.org/

**Comment by matt-nervos** [comment]
thanks @Keith-CY !
