### ISSUE TITLE
Nervos Roadmap (404 Page)

### ISSUE THREAD

**Issue by testgr123** [Magickbase/nervos-official-website#431]
Hello everyone!

It's my first post here, so if anything is wrong, please let me know.

It has come to our attention that the following page (https://www.nervos.org/about/roadmap) is a 404 one. I found that link by searching on Google for "Nervos Network Roadmap" on the first page (StartWithNervos) at https://startwithnervos.com/nervos-faq/what-is-the-roadmap-for-nervos-network.

I understand it is no longer part of the main structure and that Nervos now presents ongoing progress on the Nervos Journey page.

Since old links can still be accessed on the web, in my opinion, it could be a good practice to redirect that page to the Nervos Journey so newcomers don't think nothing is being done, which is far from being true, of course.

Thanks for your time!

Best regards,
Gustavo

**Comment by Keith-CY** [comment]
Hi Gustavo, really appreciate your advice about the redirection, the deprecated roadmap does confuse newcomers. 

Now both https://nervos.org/about/roadmap and https://archive.nervos.org/about/roadmap lead to the latest `Journey` page at https://www.nervos.org/journey

**Comment by testgr123** [comment]
Hello Keith!

Thanks for your promptness in solving this; I really appreciate it.

Best Regards,
Gustavo

**Comment by testgr123** [comment]
Solved.
