### ISSUE TITLE
Update the foundation page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/nervos-official-website#439]
Figma: https://www.figma.com/file/VctwLYgHsUgFDA3uxhLBIx/Nervos-Foundation?type=design&node-id=0%3A1&mode=design&t=vVRnjSHCmbqr4Lgx-1

**Comment by Keith-CY** [comment]
PR: https://github.com/Magickbase/nervos-official-website/pull/442
Preview: https://nervos-official-website-git-fork-painterpuppe-5147e4-magickbase.vercel.app/foundation

**Comment by matt-nervos** [comment]
thanks @PainterPuppets @Keith-CY 

I saw a few revisions:

1. change X link at top of page to https://twitter.com/RunningCKB 

2. "The Nervos Foundation is a non-profit organization whose mission is to support the long-term growth of the Nervos Network. We work to ensure the future success of Nervos by seeding the community to grow independently while driving meaningful innovation in the industry."

change "success of Nervos" to "success of the network"

3. change "CKB Ecosystem fund" link to https://ckbeco.fund/

4. Is there some way these orgs could have links when someone mouses over them?

<img width="439" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/88007636/ecde6eb0-c7d3-473a-b2ee-e46dd6beb7e0">

**Comment by Keith-CY** [comment]
Hi @matt-nervos
The new foundation page is ready at https://nervos-official-website-git-develop-magickbase.vercel.app/foundation, and will be deployed to https://nervos.org/foundation if no more revisions.

I found that https://www.nervos.foundation/ was not properly, will be checked with @poshboytl  again.

**Comment by Keith-CY** [comment]
> Hi @matt-nervos The new foundation page is ready at [nervos-official-website-git-develop-magickbase.vercel.app/foundation](https://nervos-official-website-git-develop-magickbase.vercel.app/foundation), and will be deployed to [nervos.org/foundation](https://nervos.org/foundation) if no more revisions.
> 
> I found that [nervos.foundation](https://www.nervos.foundation/) was not properly, will be checked with @poshboytl again.

https://www.nervos.foundation has been set.

**Comment by matt-nervos** [comment]
> Hi @matt-nervos The new foundation page is ready at https://nervos-official-website-git-develop-magickbase.vercel.app/foundation, and will be deployed to https://nervos.org/foundation if no more revisions.
> 
> I found that https://www.nervos.foundation/ was not properly, will be checked with @poshboytl again.

looks good, thank you @Keith-CY

**Comment by Keith-CY** [comment]
> > Hi @matt-nervos The new foundation page is ready at [nervos-official-website-git-develop-magickbase.vercel.app/foundation](https://nervos-official-website-git-develop-magickbase.vercel.app/foundation), and will be deployed to [nervos.org/foundation](https://nervos.org/foundation) if no more revisions.
> > I found that [nervos.foundation](https://www.nervos.foundation/) was not properly, will be checked with @poshboytl again.
> 
> looks good, thank you @Keith-CY

The new foundation page has been deployed and can be visited at https://nervos.foundation
