### ISSUE TITLE
Broken images for two articles within the Knowledge Base.

### ISSUE THREAD

**Issue by jordanmack** [Magickbase/nervos-official-website#449]
https://www.nervos.org/knowledge-base

![20240325172712](https://github.com/Magickbase/nervos-official-website/assets/37931/2ab2e1b9-dd75-4be9-802c-229cd68f9de2)

**Comment by Keith-CY** [comment]
Cover of **What is RIPEMD160** at https://github.com/NervosEducationHub/EducationHubArticles/blob/main/what_is-RIPEMD160_(explainCKBot)/images/image1.png

Cover of **What are Precompiles in Blockchain Technology?** at https://github.com/NervosEducationHub/EducationHubArticles/blob/main/what_are-precompiles_(explainCKBot)/images/image1.png

are broken, cc @matt-nervos

**Comment by matt-nervos** [comment]
fixed, please close
