### ISSUE TITLE
Add page view on article page

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/nervos-official-website#450]
Article page:
![image](https://github.com/Magickbase/nervos-official-website/assets/7271329/d28272d2-a0ca-4fc2-abd6-8ab60e9f51f3)

Article list page:
![image](https://github.com/Magickbase/nervos-official-website/assets/7271329/53a8744a-38f0-4ee6-950e-0bee5e93f13d)

GA code snippet

```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id={GA ID}"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', {GA ID});
</script>
```

**Comment by Keith-CY** [comment]
How is it going @PainterPuppets

**Comment by PainterPuppets** [comment]
> How is it going @PainterPuppets

Google's authentication setup is a bit complicated and is being worked on

**Comment by Keith-CY** [comment]
> > How is it going @PainterPuppets
> 
> Google's authentication setup is a bit complicated and is being worked on, and i should be able to complete it today.

Waiting for response from Adele for the authentication file

**Comment by Keith-CY** [comment]
`Page view` has been added by https://github.com/Magickbase/nervos-official-website/pull/453

<img width="1264" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/7271329/7bfbc66e-d16b-4102-abe8-f4034f098f3b">
<img width="1361" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/7271329/c20abddf-3cf6-4c78-9488-c1c5b94f6ac3">
<img width="746" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/7271329/f2e1dc4f-4d6f-412c-9ff9-9dd824db57f9">
