### ISSUE TITLE
A new page hosted on friendsofbitcoin.xyz

### ISSUE THREAD

**Issue by Keith-CY** [Magickbase/nervos-official-website#460]
Figma: 
https://www.figma.com/proto/fwJy4EGHtcN2uyjR56Gm9J/Friends-of-Bitcoin-Site?page-id=0%3A1&type=design&node-id=22-120&viewport=617%2C2425%2C0.72&t=m1vxJWnSOkDiOBKX-1&scaling=min-zoom

Only page #2

Nashville- https://lu.ma/0bwudqyt
brussels- https://lu.ma/yb8kvcbx

**Comment by Keith-CY** [comment]
Will be started soon by @PainterPuppets

**Comment by PainterPuppets** [comment]
I checked out figma, how should I get the resources for these animation files, And are these pages running in a new project, or in the `website` project?

**Comment by PainterPuppets** [comment]
I checked the proto and it's pretty AMAZING.
The file on figma seems to be just a canvas and I have no way to get the resources I want directly from figma. I've received some gifs, but still missing some resources, here's a list

 - Pixel style font

<img width="714" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/4b7f7205-1f92-4f43-9698-7f5e3ca4d23a">

 - Pointed Fonts

<img width="276" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/e2ef3d92-a863-4720-8e16-c74905849130">

 - a heart cut-out font

<img width="91" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/f754efd0-cbb2-40c1-bf3b-98a4f90a2420">


And some images.

 - A man on a horse.

<img width="223" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/910c16f4-f997-409b-bba9-b0eed29bce3f">

 - cactus

<img width="148" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/67d75dab-79a6-44c6-aa41-108f271636ae">

 - stars (This seems to be a vector pattern and there are many colors, if could give the `svg` I would be able to adjust the color in the code, which would be better)

<img width="268" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/900bad40-ffe1-4db8-adc5-c88ee9b951c2">
<img width="103" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/23deb08d-b192-4420-94b9-c208f1117a57">



 - rainbow

<img width="268" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/409f812f-1b30-4bcd-b071-dc4d7e129d9a">

 - Chocolate

<img width="84" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/0d52a46f-14a7-44e1-8c95-bc2c614204f1">

 - Home BTC background (would be better if each clip was split)
<img width="727" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/caa4b424-654b-4bee-9927-106f5f7e4849">


 - Two static figures
<img width="326" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/8f06fe17-46ed-4815-af6f-29260473ec7d">
<img width="269" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/20dfda7e-dd4f-4f35-8ec4-535b1dc385b0">

 - House background
<img width="1025" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/f9e838f1-cc17-4d40-bf6a-56271d4e7831">


And some animated material
 - Spinning BTC Coins
<img width="139" alt="image" src="https://github.com/Magickbase/nervos-official-website/assets/22258327/419857b2-95fb-4024-ba2a-0c51effd9ab8">

**Comment by TheBTCQueen** [comment]
Hey @PainterPuppets 

So these assets are not on the page that needs to be edited. 
ahrom added another page so page #2 is now page #3

Sorry for the confusion.

for reference this is the page:
![page3](https://github.com/Magickbase/nervos-official-website/assets/135681898/90891530-2a39-4009-bff1-afbb4c794317)


Thanks!!!!!

**Comment by ahromland** [comment]
hi @PainterPuppets can you try this link - https://www.figma.com/file/fwJy4EGHtcN2uyjR56Gm9J/Friends-of-Bitcoin-Site?type=design&node-id=0%3A1&mode=dev&t=iCQ1WG6nUtwDd5bd-1

see if you can retrieve all the assets from here. I'll get you the fonts very soon

**Comment by Keith-CY** [comment]
> hi @PainterPuppets can you try this link - [figma.com/file/fwJy4EGHtcN2uyjR56Gm9J/Friends-of-Bitcoin-Site?type=design&node-id=0%3A1&mode=dev&t=iCQ1WG6nUtwDd5bd-1](https://www.figma.com/file/fwJy4EGHtcN2uyjR56Gm9J/Friends-of-Bitcoin-Site?type=design&node-id=0%3A1&mode=dev&t=iCQ1WG6nUtwDd5bd-1)
> 
> see if you can retrieve all the assets from here. I'll get you the fonts very soon

It works cc @PainterPuppets

**Comment by ahromland** [comment]
here are the fonts

[Arbutus,Dela_Gothic_One.zip](https://github.com/Magickbase/nervos-official-website/files/15229154/Arbutus.Dela_Gothic_One.zip)
[Dela_Gothic_One.zip](https://github.com/Magickbase/nervos-official-website/files/15229155/Dela_Gothic_One.zip)
[deltarune.zip](https://github.com/Magickbase/nervos-official-website/files/15229156/deltarune.zip)

**Comment by ahromland** [comment]
@PainterPuppets @Keith-CY hi guys, let me know if you got everything or need anything else!

**Comment by PainterPuppets** [comment]
> @PainterPuppets @Keith-CY hi guys, let me know if you got everything or need anything else!

Thanks!!

**Comment by PainterPuppets** [comment]
I'm having two problems in the implementation, I'd appreciate an answer. @ahromland @TheBTCQueen 

1. I understand that the home page of this page should be the #3 page, and then by switching left and right can go to the #4 and #5 page, and then the #1 page and the #2 page seem to be the same, are these two pages the same page? And how do I access #1 and #2?

2. These pages don't seem to have mobile adaptations, do we need to do them?

**Comment by TheBTCQueen** [comment]
Hi,

So the only page we need built is the landing page. #3 with the buttons
connected to the luma links. We decided to scrap the other pag s due to
time and avoiding updating the pages later on.
All you need to focus on is page #3.

As for the mobile version, most people use mobile. As long as they can
navigate to the buttons that's the most important part in my opinion.
@ahrom what do you think?

**Comment by PainterPuppets** [comment]
page preview: https://friendsofbitcoin.vercel.app/

**Comment by ahromland** [comment]
@TheBTCQueen @PainterPuppets yep, i'll mock up the mobile version asap

**Comment by ahromland** [comment]
mobile version is ready in the same figgy file :)

**Comment by PainterPuppets** [comment]
Hi,
It's been updated.
Added mobile adaptation and removed the page flip, here's a preview: https://friendsofbitcoin.vercel.app/

@ahromland @TheBTCQueen

**Comment by TheBTCQueen** [comment]
@PainterPuppets let me know when the website is live!

**Comment by PainterPuppets** [comment]
> @PainterPuppets let me know when the website is live!

Hi @TheBTCQueen
Sorry for only just seeing the reply, the site is now accessible at https://www.friendsofbitcoin.xyz/
