### ISSUE TITLE
Update the Homepage

### ISSUE THREAD

**Issue by gracegui43** [Magickbase/nervos-official-website#484]
Currently, the Nervos website lacks information regarding the recent Bitcoin L2 strategy. This information is mainly available on the CKB Eco Fund's official website (which has been recently updated). To provide better guidance, it is recommended to update the Nervos website homepage.

Relevant design can be found here: [figma](https://www.figma.com/design/jOqe58xwwerxpUYFtMbstm/Nervos.org-R5?m=dev&node-id=6359-1036&t=w0w7QGrqeDIjBjvP-1)

There are 2 preferred designs. The first one use the CKB Eco Fund logo similar fonts, while the second one uses Nervos fonts. 
![Nervos Homepage V2 (1)](https://github.com/Magickbase/nervos-official-website/assets/36319023/da95247c-4623-4263-946c-c92705dcfa78)
![Nervos Homepage V2](https://github.com/Magickbase/nervos-official-website/assets/36319023/1a945473-b62e-48cd-8eac-90b2638b07e1)

**Comment by Keith-CY** [comment]
Hi @gracegui43 

I found the name in figma is `Homepage NEW`, will it be the new homepage, or just a section appended to the `Get Started` section?

And designing for mobile layout is essential.

Any idea for the design we will choose? @matt-nervos

**Comment by gracegui43** [comment]
Hi Keith, it'll be new homepage. 

Mobile version will be added shortly.

**Comment by gracegui43** [comment]
Hi @Keith-CY , mobile version updated. Maybe we can go with the CKB Eco Fund fonts to showcase different approaches.

**Comment by Keith-CY** [comment]
Any idea for the design we will choose? @Matt-RUN-CKB

**Comment by Keith-CY** [comment]
> Any idea for the design we will choose? @Matt-RUN-CKB

Style 1 is picked

**Comment by gracegui43** [comment]
> > Any idea for the design we will choose? @Matt-RUN-CKB
> 
> Style 1 is picked

Hi Keith, we've also open a discussion on the Nervos Talk. And community prefers same fonts as Nervos. We can go with this one, ie style 2.
https://talk.nervos.org/t/seeking-community-feedback-on-nervos-homepage-update/8285/10

**Comment by Keith-CY** [comment]
Will be updated by https://github.com/Magickbase/nervos-official-website/pull/493

**Comment by gracegui43** [comment]
Sure. Let me check with designer.

**Comment by gracegui43** [comment]
Yes, let's make it a little bit bigger.

**Comment by Keith-CY** [comment]
> Yes, let's make it a little bit bigger.

Page updated at https://www.nervos.org/ please check

**Comment by gracegui43** [comment]
Hi @Keith-CY , the EN version of the link should be: CKB Eco Fund instead of Nervos Eco Fund, which is the fund brand. Please update, thanks!

**Comment by Keith-CY** [comment]
> Hi @Keith-CY , the EN version of the link should be: CKB Eco Fund instead of Nervos Eco Fund, which is the fund brand. Please update, thanks!

Updated https://www.nervos.org/
<img width="1491" alt="image" src="https://github.com/user-attachments/assets/34232428-4a79-4140-9885-796de0ad5216">
