### ISSUE TITLE
Updates to "Journey" page

### ISSUE THREAD

**Issue by Matt-RUN-CKB** [Magickbase/nervos-official-website#485]
Hello Magickbase team! To keep up with current developments, I've summarized some proposed changes to the "Journey" page:

**Move from "In Progress" to "Achievements"**
Spore NFT Protocol 

**Add to "In Progress"**
CKBFiber (Lightning Network+CKB) (link: https://github.com/nervosnetwork/cfn-node)

**Move from "Upcoming" to "Achievements"**
Light Client Soft Fork

**Add to "Upcoming"** 
UTXO Stack launch (link: http://utxostack.network/ )
CKBFiber testnet (link: https://github.com/nervosnetwork/cfn-node)

**Add to "Achievements"**
Bitcoin SPV verification (link: https://x.com/utxostack/status/1803024147842511112)
RGB++ launch (link: https://hackernoon.com/building-on-bitcoin-a-beginners-guide-to-using-the-rgb-protocol)
Cobuild (link: https://talk.nervos.org/t/ckb-transaction-cobuild-protocol-overview/7702)

Remove "Kuai" from "In Progress"

fix typo in "Achievements" "eXtensidble User Defined Tokens"->"eXtensible User Defined Tokens"

**Comment by Keith-CY** [comment]
Updated at https://www.nervos.org/journey

---

In progress
- Remove `Spore NFT Protocol`
- Remove `Kuai`
- Add `CKB Fiber (Lightning Network + CKB)`
- 
Before
<img width="358" alt="In progress" src="https://github.com/user-attachments/assets/146046e0-7319-482a-846e-12efd8959b83">

After
<img width="504" alt="image" src="https://github.com/user-attachments/assets/85f76450-ca6f-409d-8f37-96c669ace862">

---

Upcoming
- Remove `Light Client Soft Fork`
- Add `UTXO Stack Launch`
- Add `CKB Fiber Testnet`

Before
<img width="336" alt="Upcoming" src="https://github.com/user-attachments/assets/ce5c23fa-044d-40e8-a131-c0a777651536">

After
<img width="352" alt="image" src="https://github.com/user-attachments/assets/ce37e608-b006-4d24-bdc8-21b783e91d10">

---

Achievement
- Add `Spore NFT Protocol`
- Add `Light Client Soft Fork`
- Add `Bitcoin SPV Verification`
- Add `RGB++ Launch`
- Add `Cobuild`

Before
<img width="537" alt="Achievements" src="https://github.com/user-attachments/assets/8a68d596-e4d0-4844-b44d-e61c3ae0dade">

After
<img width="504" alt="image" src="https://github.com/user-attachments/assets/b01bd37f-aacc-4698-ab4e-446b902f9e53">

---

Fix Typo`eXtensidble`
<img width="361" alt="image" src="https://github.com/user-attachments/assets/24d07051-cf57-4bc3-b5f8-d2b4cc46c384">
