### ISSUE TITLE
Remove Portal Wallet from Wallet Page

### ISSUE THREAD

**Issue by alejandroRbit** [Magickbase/nervos-official-website#511]
Portal Wallet will close the website on December 31, 2024. I think it should be removed from the website and no longer recommended to community members.

![image](https://github.com/user-attachments/assets/1f1020e0-e071-4275-ab82-4c76a0084856)

![image](https://github.com/user-attachments/assets/08a89a99-6139-43b9-9d2d-0e89bfccbd65)

**Comment by Keith-CY** [comment]
Portal Wallet will be removed by PR https://github.com/Magickbase/nervos-official-website/pull/512

**Comment by Keith-CY** [comment]
Portal Wallet has been removed from https://www.nervos.org/wallets
<img width="216" alt="image" src="https://github.com/user-attachments/assets/fdf725d6-eb98-4adf-b5ff-effdf900a4e2">

**Comment by alejandroRbit** [comment]
Thank you!
